### ISSUE TITLE
Error in visualizer.cpp during installation

### ISSUE THREAD

**Issue by ashish-kmr** [robotlearn/raisimpy#13] opened 2019-10-19 19:01 UTC
While trying to install raisimpy in a docker, I get the following error -- 

error: no match for call to ‘(const pybind11::detail::overload_cast_impl<raisim::HeightMap*, const std::__cxx11::basic_string<char, std::char_traits<char>, std:
:allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>) (<unresolved overloaded function type>)’

Here is the version information on the required libraries --
-- Found raisim: /root/raisim_build/include (Required is at least version "0.4.2")
-- raisim:
--   Version: 0.5.0
--   Includes: /root/raisim_build/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
-- Found raisim: /root/raisim_build/include
-- raisim:
--   Version: 0.5.0
--   Includes: /root/raisim_build/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
-- Found OGRE   
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage
--   media      : /root/raisim_build/share/OGRE/Media
-- raisimOgre:
--   Version: 0.5.1
--   Includes: /root/raisim_build/include
--   Libraries: OgreMain;OgreBites;OgreRTShaderSystem;OgreMeshLodGenerator;raisim::assimp;raisim::raisim;pthread;zzip;SDL2
-- Configuring done
-- Generating done
-- Build files have been written to: /root/raisimpy/build

**Comment by jhwangbo** [comment] 2019-10-21 07:39
the issue is addressed in #14

**Closed as completed by jhwangbo** 2019-10-21 07:39 UTC
