### ISSUE TITLE
addMesh in raisimpy/src/world.cpp 

### ISSUE THREAD

**Issue by Fleer-code** [robotlearn/raisimpy#17] opened 2019-11-17 15:49 UTC
Hello, I'm trying to compile the python wrappers from the `raisimpy.` But after I typed make -j4, an error occurred.
```
/home/wzc/raisim_workspace/raisimpy/src/world.cpp: In lambda function:
/home/wzc/raisim_workspace/raisimpy/src/world.cpp:326:82: error: no matching function for call to ‘raisim::World::addMesh(const string&, double&, raisim::Mat<3, 3>&, raisim::Vec<3>&, const string&, CollisionGroup&, CollisionGroup&)’
                return self.addMesh(file_name, mass, I, COM, material, group, mask);
                                                                                  ^
In file included from /home/wzc/raisim_workspace/raisimpy/src/world.cpp:32:
/home/wzc/raisim_build/include/raisim/World.hpp:191:9: note: candidate: ‘raisim::Mesh* raisim::World::addMesh(const string&, double, const raisim::Mat<3, 3>&, const raisim::Vec<3>&, double, const string&, CollisionGroup, CollisionGroup)’
   Mesh *addMesh(const std::string &fileName,
         ^~~~~~~
/home/wzc/raisim_build/include/raisim/World.hpp:191:9: note:   no known conversion for argument 5 from ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘double’
CMakeFiles/raisimpy.dir/build.make:218: recipe for target 'CMakeFiles/raisimpy.dir/src/world.cpp.o' failed
make[2]: *** [CMakeFiles/raisimpy.dir/src/world.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/raisimpy.dir/all' failed
make[1]: *** [CMakeFiles/raisimpy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
I find that in `raisimLib/include/World.hpp`, function `addMesh` has eight arguments. 
```
  Mesh *addMesh(const std::string &fileName,
                double mass,
                const Mat<3, 3> &inertia,
                const Vec<3> &COM,
                double scale = 1,
                const std::string &material = "",
                CollisionGroup collisionGroup = 1,
                CollisionGroup collisionMask = CollisionGroup(-1));
```
But in `aisimpy/src/world.cpp`,  `addMesh` only get seven arguments. 
`return self.addMesh(file_name, mass, I, COM, material, group, mask);`
What can I do to fix this?

**Comment by jhwangbo** [comment] 2019-11-17 16:34
The issue is addressed by #18

**Closed as completed by jhwangbo** 2019-11-17 16:34 UTC
